// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePgqN239JiOHAX6vZm-fGIuWN4_rMVE4',
    appId: '1:498688760652:android:55cd7921aa7f1d8dc04de9',
    messagingSenderId: '498688760652',
    projectId: 'mailup-7ff3d',
    storageBucket: 'mailup-7ff3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQlMDzId11tOK4S2zTvNLhUWWklLEtrdI',
    appId: '1:728119460156:ios:da1e8551fce2b8a8e75e39',
    messagingSenderId: '728119460156',
    projectId: 'mailup-7ff3d',
    storageBucket: 'mailup-7ff3d.firebasestorage.app',
    iosBundleId: 'com.example.mailUp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEujSzOtnUrHdHclVxlpMRwIWXKxm3Pgo',
    appId: '1:728119460156:web:4c5bb26bcc1cdb6be75e39',
    messagingSenderId: '728119460156',
    projectId: 'mailup-7ff3d',
    authDomain: 'mailup-7ff3d.firebaseapp.com',
    storageBucket: 'mailup-7ff3d.firebasestorage.app',
    measurementId: 'G-1ZE88L4TFQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQlMDzId11tOK4S2zTvNLhUWWklLEtrdI',
    appId: '1:728119460156:ios:da1e8551fce2b8a8e75e39',
    messagingSenderId: '728119460156',
    projectId: 'mailup-7ff3d',
    storageBucket: 'mailup-7ff3d.firebasestorage.app',
    iosBundleId: 'com.example.mailUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYkaYGxNPRlkNSDZaDk7i6xny75BAIVRo',
    appId: '1:728119460156:web:5f9fc2526ae68b4de75e39',
    messagingSenderId: '728119460156',
    projectId: 'mailup-7ff3d',
    authDomain: 'mailup-7ff3d.firebaseapp.com',
    storageBucket: 'mailup-7ff3d.firebasestorage.app',
    measurementId: 'G-YMEVT8DLLL',
  );

}